#!/bin/bash

NAME=<YOUR_USERNAME>
IMAGE_NAME="<YOUR_IMAGE_NAME>"
VERSION="1.0.0"

DOCKER_REGISTRY="<YOUR_REGISTRY>/<YOUR_PROJECT>"
DOCKER_REGISTRY_USER="<YOUR_REGISTRY_USER>"
# DOCKER_REGISTRY_PASSWORD 는 환경변수로 주입하거나 docker login 후 실행
# export DOCKER_REGISTRY_PASSWORD="..."

echo ${DOCKER_REGISTRY_PASSWORD} | docker login ${DOCKER_REGISTRY} \
    -u ${DOCKER_REGISTRY_USER} --password-stdin \
    || { echo "Docker 로그인 실패"; exit 1; }

docker tag ${NAME}-${IMAGE_NAME}:${VERSION} ${DOCKER_REGISTRY}/${NAME}-${IMAGE_NAME}:${VERSION}

docker push ${DOCKER_REGISTRY}/${NAME}-${IMAGE_NAME}:${VERSION}
